name: pulsepad
description: "Turn your phone into a low-latency game controller for PS2/PSP emulators and Linux PC"
publish_to: 'none'
version: 2.0.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  vibration: ^2.0.0
  mobile_scanner: ^5.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
